services:
  app:
    # build:
    #   context: .
    #   network: host
    #   args:
    #     - HTTP_PROXY=${HTTP_PROXY}
    #     - HTTPS_PROXY=${HTTPS_PROXY}
    #     - NO_PROXY=${NO_PROXY}
    image: ghcr.io/bipou/football-site:latest
    # container_name: football-site
    restart: always
    ports:
      - "7600:7600"
    env_file:
      - .env
    volumes:
      - /root/bipou-uploads:/app/site/uploads
    networks:
      - surrealdb_net

networks:
  surrealdb_net:
    external: true
