services:
  app:
    image: ghcr.io/bipou/ftbsite:${TAG:-cn}
    restart: always
    ports:
      - "7600:7600"
    env_file:
      - .env
    volumes:
      - /root/bipou-uploads:/app/site/uploads
    networks:
      - surrealdb_net

networks:
  surrealdb_net:
    external: true
