#![recursion_limit = "512"]

pub mod app;
pub mod components;
pub mod models;
pub mod pages;
pub mod utils;

#[cfg(feature = "ssr")]
pub mod server;

// i18n module generated by build.rs via leptos_i18n_build
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

#[cfg(feature = "hydrate")]
#[wasm_bindgen::prelude::wasm_bindgen]
pub fn hydrate() {
    use crate::app::App;
    console_error_panic_hook::set_once();
    leptos::mount::hydrate_body(App);
}
